### ISSUE TITLE
Android基础面试题 错别字等问题

### ISSUE THREAD

**Issue by vicedev** [JsonChao/Awesome-Android-Interview#1]
4.AsyncTask的缺陷和问题：
	4.并行还是串行：
		直接行execute()方法，如果需要执行executeOnExecutor(Excutor)。->直接执行execute()方法，如果需要并行执行时，执行executeOnExecutor(Excutor)。

6.android中进程的优先级？
	1.前台进程：
		如果系统内存不足时前台进程是最被杀死的->如果系统内存不足时前台进程是最晚被杀死的
	3.服务进程：
		其中运行着使用startService方法启动的ervice，虽然不被用户可见，但是却是用户关心的，例用户正在非音乐界面听的音乐或者正在非下载页面自己载的文件等->其中运行着使用startService方法启动的service，虽然不被用户可见，但是却是用户关心的，例如用户正在非音乐界面听的音乐或者正在非下载页面下载的文件等

5.空进程：
	样的进程系统是一般不会让他存在的->这样的进程系统是一般不会让他存在的

9.Context相关
	Activity和Service以及Application的Context是不一的,Activity继承自ContextThemeWraper.其他的继承自CntextWrapper.->Activity和Service以及Application的Context是不一样的,Activity继承自ContextThemeWraper.其他的继承自ContextWrapper.
	创建Toast和对话框不可以用Application的context，只能用Activity的context。->**Toast可以用Application的context吧？**

**Comment by JsonChao** [comment]
Thank your issue，错别字问题现已修正~
