### ISSUE TITLE
Activity and Fragment Life Cycle Sequence?

### ISSUE THREAD

**Issue by kinglongliu** [JsonChao/Awesome-Android-Interview#6]
Are you sure the following order is correct?
 Fragment: onAttach
 Fragment: onCreate
 Fragment: onCreateView
 Activity: onCreate
 Fragment: onActivityCreated
==============================
Shouldn't that be the right？
 Activity: onCreate
 Fragment: onAttach
 Fragment: onCreate
 Fragment: onCreateView
 Fragment: onActivityCreated

**Comment by JsonChao** [comment]
Thank your issue，问题已修复，如果发现还有其他错误可以pull requests进行修复~
